name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Vulkan SDK
      uses: hmartin5/setup-vulkan-tools@v3
      with:
        vulkan-query-version: latest
        vulkan-use-latest: true
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: neutrino-windows
        path: build/bin/Release/Neutrino.exe
